// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
// Version: 2022.1
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module run_run_test (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        p_read1,
        taskId_c_din,
        taskId_c_num_data_valid,
        taskId_c_fifo_cap,
        taskId_c_full_n,
        taskId_c_write,
        run_controlStr_REGION_T_16_ap_int_ap_int_ap_int_stream_data_7_address0,
        run_controlStr_REGION_T_16_ap_int_ap_int_ap_int_stream_data_7_ce0,
        run_controlStr_REGION_T_16_ap_int_ap_int_ap_int_stream_data_7_q0,
        run_controlStr_REGION_T_16_ap_int_ap_int_ap_int_stream_data_6_address0,
        run_controlStr_REGION_T_16_ap_int_ap_int_ap_int_stream_data_6_ce0,
        run_controlStr_REGION_T_16_ap_int_ap_int_ap_int_stream_data_6_q0,
        run_controlStr_REGION_T_16_ap_int_ap_int_ap_int_stream_data_5_address0,
        run_controlStr_REGION_T_16_ap_int_ap_int_ap_int_stream_data_5_ce0,
        run_controlStr_REGION_T_16_ap_int_ap_int_ap_int_stream_data_5_q0,
        run_controlStr_REGION_T_16_ap_int_ap_int_ap_int_stream_data_4_address0,
        run_controlStr_REGION_T_16_ap_int_ap_int_ap_int_stream_data_4_ce0,
        run_controlStr_REGION_T_16_ap_int_ap_int_ap_int_stream_data_4_q0,
        run_controlStr_REGION_T_16_ap_int_ap_int_ap_int_stream_data_3_address0,
        run_controlStr_REGION_T_16_ap_int_ap_int_ap_int_stream_data_3_ce0,
        run_controlStr_REGION_T_16_ap_int_ap_int_ap_int_stream_data_3_q0,
        run_controlStr_REGION_T_16_ap_int_ap_int_ap_int_stream_data_2_address0,
        run_controlStr_REGION_T_16_ap_int_ap_int_ap_int_stream_data_2_ce0,
        run_controlStr_REGION_T_16_ap_int_ap_int_ap_int_stream_data_2_q0,
        run_controlStr_REGION_T_16_ap_int_ap_int_ap_int_stream_data_1_address0,
        run_controlStr_REGION_T_16_ap_int_ap_int_ap_int_stream_data_1_ce0,
        run_controlStr_REGION_T_16_ap_int_ap_int_ap_int_stream_data_1_q0,
        run_controlStr_REGION_T_16_ap_int_ap_int_ap_int_stream_data_address0,
        run_controlStr_REGION_T_16_ap_int_ap_int_ap_int_stream_data_ce0,
        run_controlStr_REGION_T_16_ap_int_ap_int_ap_int_stream_data_q0,
        ap_return
);

parameter    ap_ST_fsm_pp0_stage0 = 8'd1;
parameter    ap_ST_fsm_pp0_stage1 = 8'd2;
parameter    ap_ST_fsm_pp0_stage2 = 8'd4;
parameter    ap_ST_fsm_pp0_stage3 = 8'd8;
parameter    ap_ST_fsm_pp0_stage4 = 8'd16;
parameter    ap_ST_fsm_pp0_stage5 = 8'd32;
parameter    ap_ST_fsm_pp0_stage6 = 8'd64;
parameter    ap_ST_fsm_pp0_stage7 = 8'd128;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [15:0] p_read1;
output  [15:0] taskId_c_din;
input  [3:0] taskId_c_num_data_valid;
input  [3:0] taskId_c_fifo_cap;
input   taskId_c_full_n;
output   taskId_c_write;
output  [6:0] run_controlStr_REGION_T_16_ap_int_ap_int_ap_int_stream_data_7_address0;
output   run_controlStr_REGION_T_16_ap_int_ap_int_ap_int_stream_data_7_ce0;
input  [31:0] run_controlStr_REGION_T_16_ap_int_ap_int_ap_int_stream_data_7_q0;
output  [6:0] run_controlStr_REGION_T_16_ap_int_ap_int_ap_int_stream_data_6_address0;
output   run_controlStr_REGION_T_16_ap_int_ap_int_ap_int_stream_data_6_ce0;
input  [31:0] run_controlStr_REGION_T_16_ap_int_ap_int_ap_int_stream_data_6_q0;
output  [6:0] run_controlStr_REGION_T_16_ap_int_ap_int_ap_int_stream_data_5_address0;
output   run_controlStr_REGION_T_16_ap_int_ap_int_ap_int_stream_data_5_ce0;
input  [31:0] run_controlStr_REGION_T_16_ap_int_ap_int_ap_int_stream_data_5_q0;
output  [6:0] run_controlStr_REGION_T_16_ap_int_ap_int_ap_int_stream_data_4_address0;
output   run_controlStr_REGION_T_16_ap_int_ap_int_ap_int_stream_data_4_ce0;
input  [31:0] run_controlStr_REGION_T_16_ap_int_ap_int_ap_int_stream_data_4_q0;
output  [6:0] run_controlStr_REGION_T_16_ap_int_ap_int_ap_int_stream_data_3_address0;
output   run_controlStr_REGION_T_16_ap_int_ap_int_ap_int_stream_data_3_ce0;
input  [31:0] run_controlStr_REGION_T_16_ap_int_ap_int_ap_int_stream_data_3_q0;
output  [6:0] run_controlStr_REGION_T_16_ap_int_ap_int_ap_int_stream_data_2_address0;
output   run_controlStr_REGION_T_16_ap_int_ap_int_ap_int_stream_data_2_ce0;
input  [31:0] run_controlStr_REGION_T_16_ap_int_ap_int_ap_int_stream_data_2_q0;
output  [6:0] run_controlStr_REGION_T_16_ap_int_ap_int_ap_int_stream_data_1_address0;
output   run_controlStr_REGION_T_16_ap_int_ap_int_ap_int_stream_data_1_ce0;
input  [31:0] run_controlStr_REGION_T_16_ap_int_ap_int_ap_int_stream_data_1_q0;
output  [6:0] run_controlStr_REGION_T_16_ap_int_ap_int_ap_int_stream_data_address0;
output   run_controlStr_REGION_T_16_ap_int_ap_int_ap_int_stream_data_ce0;
input  [31:0] run_controlStr_REGION_T_16_ap_int_ap_int_ap_int_stream_data_q0;
output  [0:0] ap_return;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg taskId_c_write;
reg run_controlStr_REGION_T_16_ap_int_ap_int_ap_int_stream_data_7_ce0;
reg run_controlStr_REGION_T_16_ap_int_ap_int_ap_int_stream_data_6_ce0;
reg run_controlStr_REGION_T_16_ap_int_ap_int_ap_int_stream_data_5_ce0;
reg run_controlStr_REGION_T_16_ap_int_ap_int_ap_int_stream_data_4_ce0;
reg run_controlStr_REGION_T_16_ap_int_ap_int_ap_int_stream_data_3_ce0;
reg run_controlStr_REGION_T_16_ap_int_ap_int_ap_int_stream_data_2_ce0;
reg run_controlStr_REGION_T_16_ap_int_ap_int_ap_int_stream_data_1_ce0;
reg run_controlStr_REGION_T_16_ap_int_ap_int_ap_int_stream_data_ce0;
reg[0:0] ap_return;

(* fsm_encoding = "none" *) reg   [7:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_idle_pp0;
wire    ap_CS_fsm_pp0_stage7;
wire    ap_block_state8_pp0_stage7_iter0;
wire    ap_block_state16_pp0_stage7_iter1;
wire    ap_block_state24_pp0_stage7_iter2;
wire    ap_block_pp0_stage7_subdone;
reg    taskId_c_blk_n;
reg    ap_done_reg;
wire    ap_block_pp0_stage0;
reg   [6:0] run_controlStr_REGION_T_16_ap_int_ap_int_ap_int_stream_data_addr_reg_690;
reg    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state9_pp0_stage0_iter1;
wire    ap_block_state17_pp0_stage0_iter2;
wire    ap_block_state25_pp0_stage0_iter3;
reg    ap_block_pp0_stage0_11001;
reg   [6:0] run_controlStr_REGION_T_16_ap_int_ap_int_ap_int_stream_data_addr_reg_690_pp0_iter1_reg;
reg   [6:0] run_controlStr_REGION_T_16_ap_int_ap_int_ap_int_stream_data_1_addr_reg_695;
reg   [6:0] run_controlStr_REGION_T_16_ap_int_ap_int_ap_int_stream_data_1_addr_reg_695_pp0_iter1_reg;
reg   [6:0] run_controlStr_REGION_T_16_ap_int_ap_int_ap_int_stream_data_2_addr_reg_700;
reg   [6:0] run_controlStr_REGION_T_16_ap_int_ap_int_ap_int_stream_data_2_addr_reg_700_pp0_iter1_reg;
reg   [6:0] run_controlStr_REGION_T_16_ap_int_ap_int_ap_int_stream_data_3_addr_reg_705;
reg   [6:0] run_controlStr_REGION_T_16_ap_int_ap_int_ap_int_stream_data_4_addr_reg_710;
reg   [6:0] run_controlStr_REGION_T_16_ap_int_ap_int_ap_int_stream_data_5_addr_reg_715;
reg   [6:0] run_controlStr_REGION_T_16_ap_int_ap_int_ap_int_stream_data_6_addr_reg_720;
reg   [31:0] run_controlStr_REGION_T_16_ap_int_ap_int_ap_int_stream_data_7_load_reg_730;
wire    ap_CS_fsm_pp0_stage1;
wire    ap_block_state2_pp0_stage1_iter0;
wire    ap_block_state10_pp0_stage1_iter1;
wire    ap_block_state18_pp0_stage1_iter2;
wire    ap_block_state26_pp0_stage1_iter3;
wire    ap_block_pp0_stage1_11001;
reg   [31:0] run_controlStr_REGION_T_16_ap_int_ap_int_ap_int_stream_data_7_load_reg_730_pp0_iter1_reg;
reg   [31:0] run_controlStr_REGION_T_16_ap_int_ap_int_ap_int_stream_data_7_load_reg_730_pp0_iter2_reg;
wire   [0:0] or_ln85_1_fu_305_p2;
reg   [0:0] or_ln85_1_reg_739;
wire    ap_CS_fsm_pp0_stage2;
wire    ap_block_state3_pp0_stage2_iter0;
wire    ap_block_state11_pp0_stage2_iter1;
wire    ap_block_state19_pp0_stage2_iter2;
wire    ap_block_state27_pp0_stage2_iter3;
wire    ap_block_pp0_stage2_11001;
reg   [0:0] or_ln85_1_reg_739_pp0_iter1_reg;
reg   [0:0] or_ln85_1_reg_739_pp0_iter2_reg;
reg   [0:0] or_ln85_1_reg_739_pp0_iter3_reg;
reg   [31:0] run_controlStr_REGION_T_16_ap_int_ap_int_ap_int_stream_data_6_load_reg_743;
wire    ap_CS_fsm_pp0_stage3;
wire    ap_block_state4_pp0_stage3_iter0;
wire    ap_block_state12_pp0_stage3_iter1;
wire    ap_block_state20_pp0_stage3_iter2;
wire    ap_block_state28_pp0_stage3_iter3;
wire    ap_block_pp0_stage3_11001;
reg   [31:0] run_controlStr_REGION_T_16_ap_int_ap_int_ap_int_stream_data_6_load_reg_743_pp0_iter1_reg;
wire   [0:0] or_ln85_3_fu_358_p2;
reg   [0:0] or_ln85_3_reg_752;
wire    ap_CS_fsm_pp0_stage4;
wire    ap_block_state5_pp0_stage4_iter0;
wire    ap_block_state13_pp0_stage4_iter1;
wire    ap_block_state21_pp0_stage4_iter2;
wire    ap_block_state29_pp0_stage4_iter3;
wire    ap_block_pp0_stage4_11001;
reg   [0:0] or_ln85_3_reg_752_pp0_iter1_reg;
reg   [0:0] or_ln85_3_reg_752_pp0_iter2_reg;
reg   [31:0] run_controlStr_REGION_T_16_ap_int_ap_int_ap_int_stream_data_5_load_reg_756;
wire    ap_CS_fsm_pp0_stage5;
wire    ap_block_state6_pp0_stage5_iter0;
wire    ap_block_state14_pp0_stage5_iter1;
wire    ap_block_state22_pp0_stage5_iter2;
reg    ap_block_pp0_stage5_11001;
reg   [31:0] run_controlStr_REGION_T_16_ap_int_ap_int_ap_int_stream_data_5_load_reg_756_pp0_iter1_reg;
wire   [0:0] or_ln85_5_fu_411_p2;
reg   [0:0] or_ln85_5_reg_765;
wire    ap_CS_fsm_pp0_stage6;
wire    ap_block_state7_pp0_stage6_iter0;
wire    ap_block_state15_pp0_stage6_iter1;
wire    ap_block_state23_pp0_stage6_iter2;
wire    ap_block_pp0_stage6_11001;
reg   [0:0] or_ln85_5_reg_765_pp0_iter1_reg;
reg   [0:0] or_ln85_5_reg_765_pp0_iter2_reg;
reg   [31:0] run_controlStr_REGION_T_16_ap_int_ap_int_ap_int_stream_data_4_load_reg_769;
wire    ap_block_pp0_stage7_11001;
reg   [31:0] run_controlStr_REGION_T_16_ap_int_ap_int_ap_int_stream_data_4_load_reg_769_pp0_iter1_reg;
wire   [0:0] or_ln85_7_fu_464_p2;
reg   [0:0] or_ln85_7_reg_778;
reg   [0:0] or_ln85_7_reg_778_pp0_iter2_reg;
reg   [0:0] or_ln85_7_reg_778_pp0_iter3_reg;
reg   [31:0] run_controlStr_REGION_T_16_ap_int_ap_int_ap_int_stream_data_3_load_reg_782;
reg   [31:0] run_controlStr_REGION_T_16_ap_int_ap_int_ap_int_stream_data_3_load_reg_782_pp0_iter2_reg;
wire   [0:0] or_ln85_9_fu_517_p2;
reg   [0:0] or_ln85_9_reg_791;
reg   [0:0] or_ln85_9_reg_791_pp0_iter2_reg;
reg   [0:0] or_ln85_9_reg_791_pp0_iter3_reg;
reg   [31:0] run_controlStr_REGION_T_16_ap_int_ap_int_ap_int_stream_data_2_load_reg_795;
wire   [0:0] or_ln85_11_fu_570_p2;
reg   [0:0] or_ln85_11_reg_804;
reg   [0:0] or_ln85_11_reg_804_pp0_iter2_reg;
reg   [31:0] run_controlStr_REGION_T_16_ap_int_ap_int_ap_int_stream_data_1_load_reg_808;
wire   [0:0] or_ln85_13_fu_623_p2;
reg   [0:0] or_ln85_13_reg_817;
reg   [0:0] or_ln85_13_reg_817_pp0_iter2_reg;
reg   [31:0] run_controlStr_REGION_T_16_ap_int_ap_int_ap_int_stream_data_load_reg_821;
wire   [0:0] or_ln85_15_fu_676_p2;
reg   [0:0] or_ln85_15_reg_830;
reg   [0:0] or_ln85_15_reg_830_pp0_iter3_reg;
reg   [0:0] tmp_24_reg_834;
reg    ap_enable_reg_pp0_iter0_reg;
wire    ap_block_pp0_stage4_subdone;
wire    grp_find_region_fu_198_ap_start;
wire    grp_find_region_fu_198_ap_done;
wire    grp_find_region_fu_198_ap_idle;
wire    grp_find_region_fu_198_ap_ready;
reg    grp_find_region_fu_198_ap_ce;
wire   [4:0] grp_find_region_fu_198_ap_return;
reg    ap_predicate_op195_call_state19;
wire    ap_block_state3_pp0_stage2_iter0_ignore_call0;
wire    ap_block_state11_pp0_stage2_iter1_ignore_call0;
wire    ap_block_state19_pp0_stage2_iter2_ignore_call0;
wire    ap_block_state27_pp0_stage2_iter3_ignore_call0;
wire    ap_block_pp0_stage2_11001_ignoreCallOp195;
wire    ap_block_state4_pp0_stage3_iter0_ignore_call0;
wire    ap_block_state12_pp0_stage3_iter1_ignore_call0;
wire    ap_block_state20_pp0_stage3_iter2_ignore_call0;
wire    ap_block_state28_pp0_stage3_iter3_ignore_call0;
wire    ap_block_pp0_stage3_11001_ignoreCallOp196;
wire    ap_block_state5_pp0_stage4_iter0_ignore_call0;
wire    ap_block_state13_pp0_stage4_iter1_ignore_call0;
wire    ap_block_state21_pp0_stage4_iter2_ignore_call0;
wire    ap_block_state29_pp0_stage4_iter3_ignore_call0;
wire    ap_block_pp0_stage4_11001_ignoreCallOp197;
wire    ap_block_state6_pp0_stage5_iter0_ignore_call0;
wire    ap_block_state14_pp0_stage5_iter1_ignore_call0;
wire    ap_block_state22_pp0_stage5_iter2_ignore_call0;
reg    ap_block_pp0_stage5_11001_ignoreCallOp198;
wire    ap_block_state7_pp0_stage6_iter0_ignore_call0;
wire    ap_block_state15_pp0_stage6_iter1_ignore_call0;
wire    ap_block_state23_pp0_stage6_iter2_ignore_call0;
wire    ap_block_pp0_stage6_11001_ignoreCallOp199;
wire    ap_block_state8_pp0_stage7_iter0_ignore_call0;
wire    ap_block_state16_pp0_stage7_iter1_ignore_call0;
wire    ap_block_state24_pp0_stage7_iter2_ignore_call0;
wire    ap_block_pp0_stage7_11001_ignoreCallOp200;
reg    ap_block_state1_pp0_stage0_iter0_ignore_call0;
wire    ap_block_state9_pp0_stage0_iter1_ignore_call0;
wire    ap_block_state17_pp0_stage0_iter2_ignore_call0;
wire    ap_block_state25_pp0_stage0_iter3_ignore_call0;
reg    ap_block_pp0_stage0_11001_ignoreCallOp201;
wire    ap_block_state2_pp0_stage1_iter0_ignore_call0;
wire    ap_block_state10_pp0_stage1_iter1_ignore_call0;
wire    ap_block_state18_pp0_stage1_iter2_ignore_call0;
wire    ap_block_state26_pp0_stage1_iter3_ignore_call0;
wire    ap_block_pp0_stage1_11001_ignoreCallOp202;
reg   [0:0] ap_phi_mux_error_write_assign_phi_fu_191_p4;
wire   [0:0] ap_phi_reg_pp0_iter0_error_write_assign_reg_187;
reg   [0:0] ap_phi_reg_pp0_iter1_error_write_assign_reg_187;
reg   [0:0] ap_phi_reg_pp0_iter2_error_write_assign_reg_187;
reg   [0:0] ap_phi_reg_pp0_iter3_error_write_assign_reg_187;
reg    grp_find_region_fu_198_ap_start_reg;
reg    ap_predicate_op195_call_state19_state18;
wire    ap_block_pp0_stage2;
wire   [63:0] zext_ln80_fu_246_p1;
reg    ap_block_pp0_stage0_01001;
wire    ap_block_pp0_stage4;
wire    ap_block_pp0_stage6;
wire    ap_block_pp0_stage3;
wire    ap_block_pp0_stage5;
wire    ap_block_pp0_stage7;
reg   [31:0] grp_fu_210_p0;
wire    ap_block_pp0_stage1;
reg   [31:0] grp_fu_216_p0;
reg   [31:0] grp_fu_222_p0;
wire   [31:0] bitcast_ln85_fu_258_p1;
wire   [7:0] tmp_1_fu_261_p4;
wire   [22:0] trunc_ln85_fu_271_p1;
wire   [0:0] icmp_ln85_1_fu_281_p2;
wire   [0:0] icmp_ln85_fu_275_p2;
wire   [0:0] grp_fu_216_p2;
wire   [0:0] grp_fu_222_p2;
wire   [0:0] or_ln85_fu_287_p2;
wire   [0:0] or_ln85_2_fu_293_p2;
wire   [0:0] and_ln85_fu_299_p2;
wire   [0:0] grp_fu_210_p2;
wire   [31:0] bitcast_ln85_1_fu_311_p1;
wire   [7:0] tmp_5_fu_314_p4;
wire   [22:0] trunc_ln85_1_fu_324_p1;
wire   [0:0] icmp_ln85_3_fu_334_p2;
wire   [0:0] icmp_ln85_2_fu_328_p2;
wire   [0:0] or_ln85_4_fu_340_p2;
wire   [0:0] or_ln85_6_fu_346_p2;
wire   [0:0] and_ln85_1_fu_352_p2;
wire   [31:0] bitcast_ln85_2_fu_364_p1;
wire   [7:0] tmp_9_fu_367_p4;
wire   [22:0] trunc_ln85_2_fu_377_p1;
wire   [0:0] icmp_ln85_5_fu_387_p2;
wire   [0:0] icmp_ln85_4_fu_381_p2;
wire   [0:0] or_ln85_8_fu_393_p2;
wire   [0:0] or_ln85_10_fu_399_p2;
wire   [0:0] and_ln85_2_fu_405_p2;
wire   [31:0] bitcast_ln85_3_fu_417_p1;
wire   [7:0] tmp_7_fu_420_p4;
wire   [22:0] trunc_ln85_3_fu_430_p1;
wire   [0:0] icmp_ln85_7_fu_440_p2;
wire   [0:0] icmp_ln85_6_fu_434_p2;
wire   [0:0] or_ln85_12_fu_446_p2;
wire   [0:0] or_ln85_14_fu_452_p2;
wire   [0:0] and_ln85_3_fu_458_p2;
wire   [31:0] bitcast_ln85_4_fu_470_p1;
wire   [7:0] tmp_12_fu_473_p4;
wire   [22:0] trunc_ln85_4_fu_483_p1;
wire   [0:0] icmp_ln85_9_fu_493_p2;
wire   [0:0] icmp_ln85_8_fu_487_p2;
wire   [0:0] or_ln85_16_fu_499_p2;
wire   [0:0] or_ln85_17_fu_505_p2;
wire   [0:0] and_ln85_4_fu_511_p2;
wire   [31:0] bitcast_ln85_5_fu_523_p1;
wire   [7:0] tmp_15_fu_526_p4;
wire   [22:0] trunc_ln85_5_fu_536_p1;
wire   [0:0] icmp_ln85_11_fu_546_p2;
wire   [0:0] icmp_ln85_10_fu_540_p2;
wire   [0:0] or_ln85_18_fu_552_p2;
wire   [0:0] or_ln85_19_fu_558_p2;
wire   [0:0] and_ln85_5_fu_564_p2;
wire   [31:0] bitcast_ln85_6_fu_576_p1;
wire   [7:0] tmp_18_fu_579_p4;
wire   [22:0] trunc_ln85_6_fu_589_p1;
wire   [0:0] icmp_ln85_13_fu_599_p2;
wire   [0:0] icmp_ln85_12_fu_593_p2;
wire   [0:0] or_ln85_20_fu_605_p2;
wire   [0:0] or_ln85_21_fu_611_p2;
wire   [0:0] and_ln85_6_fu_617_p2;
wire   [31:0] bitcast_ln85_7_fu_629_p1;
wire   [7:0] tmp_21_fu_632_p4;
wire   [22:0] trunc_ln85_7_fu_642_p1;
wire   [0:0] icmp_ln85_15_fu_652_p2;
wire   [0:0] icmp_ln85_14_fu_646_p2;
wire   [0:0] or_ln85_22_fu_658_p2;
wire   [0:0] or_ln85_23_fu_664_p2;
wire   [0:0] and_ln85_7_fu_670_p2;
reg    grp_fu_210_ce;
reg    ap_predicate_op89_fcmp_state6;
reg    ap_predicate_op107_fcmp_state8;
reg    ap_predicate_op125_fcmp_state11;
reg    ap_predicate_op143_fcmp_state13;
reg    ap_predicate_op161_fcmp_state15;
reg    ap_predicate_op179_fcmp_state17;
wire    ap_block_pp0_stage1_00001;
wire    ap_block_pp0_stage3_00001;
wire    ap_block_pp0_stage5_00001;
wire    ap_block_pp0_stage7_00001;
wire    ap_block_pp0_stage2_00001;
wire    ap_block_pp0_stage4_00001;
wire    ap_block_pp0_stage6_00001;
reg    ap_block_pp0_stage0_00001;
reg    grp_fu_216_ce;
reg    ap_predicate_op90_fcmp_state6;
reg    ap_predicate_op108_fcmp_state8;
reg    ap_predicate_op126_fcmp_state11;
reg    ap_predicate_op144_fcmp_state13;
reg    ap_predicate_op162_fcmp_state15;
reg    ap_predicate_op180_fcmp_state17;
reg    grp_fu_222_ce;
reg    ap_predicate_op91_fcmp_state6;
reg    ap_predicate_op109_fcmp_state8;
reg    ap_predicate_op127_fcmp_state11;
reg    ap_predicate_op145_fcmp_state13;
reg    ap_predicate_op163_fcmp_state15;
reg    ap_predicate_op181_fcmp_state17;
reg   [0:0] ap_return_preg;
reg   [7:0] ap_NS_fsm;
reg    ap_block_pp0_stage0_subdone;
reg    ap_idle_pp0_1to3;
wire    ap_block_pp0_stage1_subdone;
wire    ap_block_pp0_stage2_subdone;
wire    ap_block_pp0_stage3_subdone;
reg    ap_idle_pp0_0to2;
reg    ap_reset_idle_pp0;
reg    ap_block_pp0_stage5_subdone;
wire    ap_block_pp0_stage6_subdone;
wire    ap_enable_pp0;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 8'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_enable_reg_pp0_iter0_reg = 1'b0;
#0 grp_find_region_fu_198_ap_start_reg = 1'b0;
#0 ap_return_preg = 1'd0;
end

run_find_region grp_find_region_fu_198(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_find_region_fu_198_ap_start),
    .ap_done(grp_find_region_fu_198_ap_done),
    .ap_idle(grp_find_region_fu_198_ap_idle),
    .ap_ready(grp_find_region_fu_198_ap_ready),
    .ap_ce(grp_find_region_fu_198_ap_ce),
    .d_read(run_controlStr_REGION_T_16_ap_int_ap_int_ap_int_stream_data_7_load_reg_730_pp0_iter2_reg),
    .d_read_23(run_controlStr_REGION_T_16_ap_int_ap_int_ap_int_stream_data_6_load_reg_743_pp0_iter1_reg),
    .d_read_24(run_controlStr_REGION_T_16_ap_int_ap_int_ap_int_stream_data_5_load_reg_756_pp0_iter1_reg),
    .d_read_25(run_controlStr_REGION_T_16_ap_int_ap_int_ap_int_stream_data_4_load_reg_769_pp0_iter1_reg),
    .d_read_26(run_controlStr_REGION_T_16_ap_int_ap_int_ap_int_stream_data_3_load_reg_782_pp0_iter2_reg),
    .d_read_27(run_controlStr_REGION_T_16_ap_int_ap_int_ap_int_stream_data_2_load_reg_795),
    .d_read_28(run_controlStr_REGION_T_16_ap_int_ap_int_ap_int_stream_data_1_load_reg_808),
    .d_read_29(run_controlStr_REGION_T_16_ap_int_ap_int_ap_int_stream_data_load_reg_821),
    .ap_return(grp_find_region_fu_198_ap_return)
);

run_fcmp_32ns_32ns_1_2_no_dsp_1_x #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 1 ))
fcmp_32ns_32ns_1_2_no_dsp_1_x_U25(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_210_p0),
    .din1(32'd0),
    .ce(grp_fu_210_ce),
    .opcode(5'd8),
    .dout(grp_fu_210_p2)
);

run_fcmp_32ns_32ns_1_2_no_dsp_1_x #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 1 ))
fcmp_32ns_32ns_1_2_no_dsp_1_x_U26(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_216_p0),
    .din1(32'd2139095040),
    .ce(grp_fu_216_ce),
    .opcode(5'd1),
    .dout(grp_fu_216_p2)
);

run_fcmp_32ns_32ns_1_2_no_dsp_1_x #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 1 ))
fcmp_32ns_32ns_1_2_no_dsp_1_x_U27(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_222_p0),
    .din1(32'd4286578688),
    .ce(grp_fu_222_ce),
    .opcode(5'd1),
    .dout(grp_fu_222_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage4_subdone) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= ap_start;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage7_subdone) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage7_subdone) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage4_subdone) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
            ap_enable_reg_pp0_iter3 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage7_subdone) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_preg <= 1'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage4_11001) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
            ap_return_preg <= ap_phi_mux_error_write_assign_phi_fu_191_p4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_find_region_fu_198_ap_start_reg <= 1'b0;
    end else begin
        if (((ap_predicate_op195_call_state19_state18 == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            grp_find_region_fu_198_ap_start_reg <= 1'b1;
        end else if ((grp_find_region_fu_198_ap_ready == 1'b1)) begin
            grp_find_region_fu_198_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3) & ((or_ln85_1_reg_739_pp0_iter3_reg == 1'd1) | ((or_ln85_3_reg_752_pp0_iter2_reg == 1'd1) | ((or_ln85_5_reg_765_pp0_iter2_reg == 1'd1) | ((or_ln85_7_reg_778_pp0_iter3_reg == 1'd1) | ((or_ln85_9_reg_791_pp0_iter2_reg == 1'd1) | ((or_ln85_11_reg_804_pp0_iter2_reg == 1'd1) | ((or_ln85_15_reg_830_pp0_iter3_reg == 1'd1) | (or_ln85_13_reg_817_pp0_iter2_reg == 1'd1)))))))))) begin
        ap_phi_reg_pp0_iter3_error_write_assign_reg_187 <= 1'd1;
    end else if (((1'b0 == ap_block_pp0_stage7_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
        ap_phi_reg_pp0_iter3_error_write_assign_reg_187 <= ap_phi_reg_pp0_iter2_error_write_assign_reg_187;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage7_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
        ap_phi_reg_pp0_iter1_error_write_assign_reg_187 <= ap_phi_reg_pp0_iter0_error_write_assign_reg_187;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage7_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
        ap_phi_reg_pp0_iter2_error_write_assign_reg_187 <= ap_phi_reg_pp0_iter1_error_write_assign_reg_187;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage5_11001) & (or_ln85_9_reg_791 == 1'd0) & (or_ln85_7_reg_778 == 1'd0) & (or_ln85_5_reg_765 == 1'd0) & (or_ln85_3_reg_752_pp0_iter1_reg == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage5) & (or_ln85_1_reg_739_pp0_iter1_reg == 1'd0))) begin
        or_ln85_11_reg_804 <= or_ln85_11_fu_570_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage5_11001) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
        or_ln85_11_reg_804_pp0_iter2_reg <= or_ln85_11_reg_804;
        run_controlStr_REGION_T_16_ap_int_ap_int_ap_int_stream_data_5_load_reg_756_pp0_iter1_reg <= run_controlStr_REGION_T_16_ap_int_ap_int_ap_int_stream_data_5_load_reg_756;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage7_11001) & (or_ln85_11_reg_804 == 1'd0) & (or_ln85_9_reg_791 == 1'd0) & (or_ln85_7_reg_778 == 1'd0) & (or_ln85_5_reg_765_pp0_iter1_reg == 1'd0) & (or_ln85_3_reg_752_pp0_iter1_reg == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage7) & (or_ln85_1_reg_739_pp0_iter1_reg == 1'd0))) begin
        or_ln85_13_reg_817 <= or_ln85_13_fu_623_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage7_11001) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
        or_ln85_13_reg_817_pp0_iter2_reg <= or_ln85_13_reg_817;
        run_controlStr_REGION_T_16_ap_int_ap_int_ap_int_stream_data_4_load_reg_769_pp0_iter1_reg <= run_controlStr_REGION_T_16_ap_int_ap_int_ap_int_stream_data_4_load_reg_769;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (or_ln85_13_reg_817 == 1'd0) & (or_ln85_11_reg_804 == 1'd0) & (or_ln85_9_reg_791 == 1'd0) & (or_ln85_7_reg_778_pp0_iter2_reg == 1'd0) & (or_ln85_5_reg_765_pp0_iter1_reg == 1'd0) & (or_ln85_3_reg_752_pp0_iter1_reg == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage1) & (or_ln85_1_reg_739_pp0_iter1_reg == 1'd0))) begin
        or_ln85_15_reg_830 <= or_ln85_15_fu_676_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        or_ln85_15_reg_830_pp0_iter3_reg <= or_ln85_15_reg_830;
        run_controlStr_REGION_T_16_ap_int_ap_int_ap_int_stream_data_3_load_reg_782_pp0_iter2_reg <= run_controlStr_REGION_T_16_ap_int_ap_int_ap_int_stream_data_3_load_reg_782;
        run_controlStr_REGION_T_16_ap_int_ap_int_ap_int_stream_data_7_load_reg_730 <= run_controlStr_REGION_T_16_ap_int_ap_int_ap_int_stream_data_7_q0;
        run_controlStr_REGION_T_16_ap_int_ap_int_ap_int_stream_data_7_load_reg_730_pp0_iter1_reg <= run_controlStr_REGION_T_16_ap_int_ap_int_ap_int_stream_data_7_load_reg_730;
        run_controlStr_REGION_T_16_ap_int_ap_int_ap_int_stream_data_7_load_reg_730_pp0_iter2_reg <= run_controlStr_REGION_T_16_ap_int_ap_int_ap_int_stream_data_7_load_reg_730_pp0_iter1_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        or_ln85_1_reg_739 <= or_ln85_1_fu_305_p2;
        or_ln85_1_reg_739_pp0_iter1_reg <= or_ln85_1_reg_739;
        or_ln85_1_reg_739_pp0_iter2_reg <= or_ln85_1_reg_739_pp0_iter1_reg;
        or_ln85_1_reg_739_pp0_iter3_reg <= or_ln85_1_reg_739_pp0_iter2_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage4_11001) & (1'b1 == ap_CS_fsm_pp0_stage4) & (or_ln85_1_reg_739 == 1'd0))) begin
        or_ln85_3_reg_752 <= or_ln85_3_fu_358_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage4_11001) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        or_ln85_3_reg_752_pp0_iter1_reg <= or_ln85_3_reg_752;
        or_ln85_3_reg_752_pp0_iter2_reg <= or_ln85_3_reg_752_pp0_iter1_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage6_11001) & (or_ln85_3_reg_752 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage6) & (or_ln85_1_reg_739 == 1'd0))) begin
        or_ln85_5_reg_765 <= or_ln85_5_fu_411_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage6_11001) & (1'b1 == ap_CS_fsm_pp0_stage6))) begin
        or_ln85_5_reg_765_pp0_iter1_reg <= or_ln85_5_reg_765;
        or_ln85_5_reg_765_pp0_iter2_reg <= or_ln85_5_reg_765_pp0_iter1_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (or_ln85_5_reg_765 == 1'd0) & (or_ln85_3_reg_752 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (or_ln85_1_reg_739 == 1'd0))) begin
        or_ln85_7_reg_778 <= or_ln85_7_fu_464_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        or_ln85_7_reg_778_pp0_iter2_reg <= or_ln85_7_reg_778;
        or_ln85_7_reg_778_pp0_iter3_reg <= or_ln85_7_reg_778_pp0_iter2_reg;
        run_controlStr_REGION_T_16_ap_int_ap_int_ap_int_stream_data_1_addr_reg_695 <= zext_ln80_fu_246_p1;
        run_controlStr_REGION_T_16_ap_int_ap_int_ap_int_stream_data_1_addr_reg_695_pp0_iter1_reg <= run_controlStr_REGION_T_16_ap_int_ap_int_ap_int_stream_data_1_addr_reg_695;
        run_controlStr_REGION_T_16_ap_int_ap_int_ap_int_stream_data_2_addr_reg_700 <= zext_ln80_fu_246_p1;
        run_controlStr_REGION_T_16_ap_int_ap_int_ap_int_stream_data_2_addr_reg_700_pp0_iter1_reg <= run_controlStr_REGION_T_16_ap_int_ap_int_ap_int_stream_data_2_addr_reg_700;
        run_controlStr_REGION_T_16_ap_int_ap_int_ap_int_stream_data_3_addr_reg_705 <= zext_ln80_fu_246_p1;
        run_controlStr_REGION_T_16_ap_int_ap_int_ap_int_stream_data_4_addr_reg_710 <= zext_ln80_fu_246_p1;
        run_controlStr_REGION_T_16_ap_int_ap_int_ap_int_stream_data_5_addr_reg_715 <= zext_ln80_fu_246_p1;
        run_controlStr_REGION_T_16_ap_int_ap_int_ap_int_stream_data_6_addr_reg_720 <= zext_ln80_fu_246_p1;
        run_controlStr_REGION_T_16_ap_int_ap_int_ap_int_stream_data_addr_reg_690 <= zext_ln80_fu_246_p1;
        run_controlStr_REGION_T_16_ap_int_ap_int_ap_int_stream_data_addr_reg_690_pp0_iter1_reg <= run_controlStr_REGION_T_16_ap_int_ap_int_ap_int_stream_data_addr_reg_690;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage3_11001) & (or_ln85_7_reg_778 == 1'd0) & (or_ln85_5_reg_765 == 1'd0) & (or_ln85_3_reg_752 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage3) & (or_ln85_1_reg_739_pp0_iter1_reg == 1'd0))) begin
        or_ln85_9_reg_791 <= or_ln85_9_fu_517_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        or_ln85_9_reg_791_pp0_iter2_reg <= or_ln85_9_reg_791;
        or_ln85_9_reg_791_pp0_iter3_reg <= or_ln85_9_reg_791_pp0_iter2_reg;
        run_controlStr_REGION_T_16_ap_int_ap_int_ap_int_stream_data_6_load_reg_743_pp0_iter1_reg <= run_controlStr_REGION_T_16_ap_int_ap_int_ap_int_stream_data_6_load_reg_743;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage6_11001) & (or_ln85_11_reg_804 == 1'd0) & (or_ln85_9_reg_791 == 1'd0) & (or_ln85_7_reg_778 == 1'd0) & (or_ln85_5_reg_765 == 1'd0) & (or_ln85_3_reg_752_pp0_iter1_reg == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage6) & (or_ln85_1_reg_739_pp0_iter1_reg == 1'd0))) begin
        run_controlStr_REGION_T_16_ap_int_ap_int_ap_int_stream_data_1_load_reg_808 <= run_controlStr_REGION_T_16_ap_int_ap_int_ap_int_stream_data_1_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage4_11001) & (or_ln85_9_reg_791 == 1'd0) & (or_ln85_7_reg_778 == 1'd0) & (or_ln85_5_reg_765 == 1'd0) & (or_ln85_3_reg_752 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage4) & (or_ln85_1_reg_739_pp0_iter1_reg == 1'd0))) begin
        run_controlStr_REGION_T_16_ap_int_ap_int_ap_int_stream_data_2_load_reg_795 <= run_controlStr_REGION_T_16_ap_int_ap_int_ap_int_stream_data_2_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (or_ln85_7_reg_778 == 1'd0) & (or_ln85_5_reg_765 == 1'd0) & (or_ln85_3_reg_752 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage1) & (or_ln85_1_reg_739 == 1'd0))) begin
        run_controlStr_REGION_T_16_ap_int_ap_int_ap_int_stream_data_3_load_reg_782 <= run_controlStr_REGION_T_16_ap_int_ap_int_ap_int_stream_data_3_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage7_11001) & (or_ln85_5_reg_765 == 1'd0) & (or_ln85_3_reg_752 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage7) & (or_ln85_1_reg_739 == 1'd0))) begin
        run_controlStr_REGION_T_16_ap_int_ap_int_ap_int_stream_data_4_load_reg_769 <= run_controlStr_REGION_T_16_ap_int_ap_int_ap_int_stream_data_4_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage5_11001) & (or_ln85_3_reg_752 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage5) & (or_ln85_1_reg_739 == 1'd0))) begin
        run_controlStr_REGION_T_16_ap_int_ap_int_ap_int_stream_data_5_load_reg_756 <= run_controlStr_REGION_T_16_ap_int_ap_int_ap_int_stream_data_5_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3) & (or_ln85_1_reg_739 == 1'd0))) begin
        run_controlStr_REGION_T_16_ap_int_ap_int_ap_int_stream_data_6_load_reg_743 <= run_controlStr_REGION_T_16_ap_int_ap_int_ap_int_stream_data_6_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (or_ln85_13_reg_817 == 1'd0) & (or_ln85_11_reg_804 == 1'd0) & (or_ln85_9_reg_791 == 1'd0) & (or_ln85_7_reg_778 == 1'd0) & (or_ln85_5_reg_765_pp0_iter1_reg == 1'd0) & (or_ln85_3_reg_752_pp0_iter1_reg == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (or_ln85_1_reg_739_pp0_iter1_reg == 1'd0))) begin
        run_controlStr_REGION_T_16_ap_int_ap_int_ap_int_stream_data_load_reg_821 <= run_controlStr_REGION_T_16_ap_int_ap_int_ap_int_stream_data_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage3_11001) & (or_ln85_15_reg_830_pp0_iter3_reg == 1'd0) & (or_ln85_13_reg_817_pp0_iter2_reg == 1'd0) & (or_ln85_11_reg_804_pp0_iter2_reg == 1'd0) & (or_ln85_9_reg_791_pp0_iter2_reg == 1'd0) & (or_ln85_7_reg_778_pp0_iter3_reg == 1'd0) & (or_ln85_5_reg_765_pp0_iter2_reg == 1'd0) & (or_ln85_3_reg_752_pp0_iter2_reg == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage3) & (or_ln85_1_reg_739_pp0_iter3_reg == 1'd0))) begin
        tmp_24_reg_834 <= grp_find_region_fu_198_ap_return[32'd4];
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage4_subdone) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        ap_enable_reg_pp0_iter0 = ap_start;
    end else begin
        ap_enable_reg_pp0_iter0 = ap_enable_reg_pp0_iter0_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0_0to2 = 1'b1;
    end else begin
        ap_idle_pp0_0to2 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0))) begin
        ap_idle_pp0_1to3 = 1'b1;
    end else begin
        ap_idle_pp0_1to3 = 1'b0;
    end
end

always @ (*) begin
    if (((or_ln85_15_reg_830_pp0_iter3_reg == 1'd0) & (or_ln85_13_reg_817_pp0_iter2_reg == 1'd0) & (or_ln85_11_reg_804_pp0_iter2_reg == 1'd0) & (or_ln85_9_reg_791_pp0_iter3_reg == 1'd0) & (or_ln85_7_reg_778_pp0_iter3_reg == 1'd0) & (or_ln85_5_reg_765_pp0_iter2_reg == 1'd0) & (or_ln85_3_reg_752_pp0_iter2_reg == 1'd0) & (or_ln85_1_reg_739_pp0_iter3_reg == 1'd0))) begin
        ap_phi_mux_error_write_assign_phi_fu_191_p4 = tmp_24_reg_834;
    end else begin
        ap_phi_mux_error_write_assign_phi_fu_191_p4 = ap_phi_reg_pp0_iter3_error_write_assign_reg_187;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage7_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0_0to2 == 1'b1))) begin
        ap_reset_idle_pp0 = 1'b1;
    end else begin
        ap_reset_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage4_11001) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        ap_return = ap_phi_mux_error_write_assign_phi_fu_191_p4;
    end else begin
        ap_return = ap_return_preg;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage1_11001_ignoreCallOp202) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001_ignoreCallOp201) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage7_11001_ignoreCallOp200) & (1'b1 == ap_CS_fsm_pp0_stage7)) | ((1'b0 == ap_block_pp0_stage6_11001_ignoreCallOp199) & (1'b1 == ap_CS_fsm_pp0_stage6)) | ((1'b0 == ap_block_pp0_stage5_11001_ignoreCallOp198) & (1'b1 == ap_CS_fsm_pp0_stage5)) | ((1'b0 == ap_block_pp0_stage4_11001_ignoreCallOp197) & (1'b1 == ap_CS_fsm_pp0_stage4)) | ((1'b0 == ap_block_pp0_stage3_11001_ignoreCallOp196) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b0 == ap_block_pp0_stage2_11001_ignoreCallOp195) & (1'b1 == ap_CS_fsm_pp0_stage2)))) begin
        grp_find_region_fu_198_ap_ce = 1'b1;
    end else begin
        grp_find_region_fu_198_ap_ce = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage7_11001) & (1'b1 == ap_CS_fsm_pp0_stage7)) | ((1'b0 == ap_block_pp0_stage6_11001) & (1'b1 == ap_CS_fsm_pp0_stage6)) | ((1'b0 == ap_block_pp0_stage5_11001) & (1'b1 == ap_CS_fsm_pp0_stage5)) | ((1'b0 == ap_block_pp0_stage4_11001) & (1'b1 == ap_CS_fsm_pp0_stage4)) | ((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        grp_fu_210_ce = 1'b1;
    end else begin
        grp_fu_210_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_210_p0 = run_controlStr_REGION_T_16_ap_int_ap_int_ap_int_stream_data_q0;
    end else if (((1'b0 == ap_block_pp0_stage6) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6))) begin
        grp_fu_210_p0 = run_controlStr_REGION_T_16_ap_int_ap_int_ap_int_stream_data_1_q0;
    end else if (((1'b0 == ap_block_pp0_stage4) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        grp_fu_210_p0 = run_controlStr_REGION_T_16_ap_int_ap_int_ap_int_stream_data_2_q0;
    end else if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        grp_fu_210_p0 = run_controlStr_REGION_T_16_ap_int_ap_int_ap_int_stream_data_3_load_reg_782;
    end else if (((1'b0 == ap_block_pp0_stage7) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
        grp_fu_210_p0 = run_controlStr_REGION_T_16_ap_int_ap_int_ap_int_stream_data_4_q0;
    end else if (((1'b0 == ap_block_pp0_stage5) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
        grp_fu_210_p0 = run_controlStr_REGION_T_16_ap_int_ap_int_ap_int_stream_data_5_q0;
    end else if (((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        grp_fu_210_p0 = run_controlStr_REGION_T_16_ap_int_ap_int_ap_int_stream_data_6_q0;
    end else if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_210_p0 = run_controlStr_REGION_T_16_ap_int_ap_int_ap_int_stream_data_7_q0;
    end else begin
        grp_fu_210_p0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage7_11001) & (1'b1 == ap_CS_fsm_pp0_stage7)) | ((1'b0 == ap_block_pp0_stage6_11001) & (1'b1 == ap_CS_fsm_pp0_stage6)) | ((1'b0 == ap_block_pp0_stage5_11001) & (1'b1 == ap_CS_fsm_pp0_stage5)) | ((1'b0 == ap_block_pp0_stage4_11001) & (1'b1 == ap_CS_fsm_pp0_stage4)) | ((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        grp_fu_216_ce = 1'b1;
    end else begin
        grp_fu_216_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_216_p0 = run_controlStr_REGION_T_16_ap_int_ap_int_ap_int_stream_data_q0;
    end else if (((1'b0 == ap_block_pp0_stage6) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6))) begin
        grp_fu_216_p0 = run_controlStr_REGION_T_16_ap_int_ap_int_ap_int_stream_data_1_q0;
    end else if (((1'b0 == ap_block_pp0_stage4) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        grp_fu_216_p0 = run_controlStr_REGION_T_16_ap_int_ap_int_ap_int_stream_data_2_q0;
    end else if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        grp_fu_216_p0 = run_controlStr_REGION_T_16_ap_int_ap_int_ap_int_stream_data_3_load_reg_782;
    end else if (((1'b0 == ap_block_pp0_stage7) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
        grp_fu_216_p0 = run_controlStr_REGION_T_16_ap_int_ap_int_ap_int_stream_data_4_q0;
    end else if (((1'b0 == ap_block_pp0_stage5) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
        grp_fu_216_p0 = run_controlStr_REGION_T_16_ap_int_ap_int_ap_int_stream_data_5_q0;
    end else if (((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        grp_fu_216_p0 = run_controlStr_REGION_T_16_ap_int_ap_int_ap_int_stream_data_6_q0;
    end else if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_216_p0 = run_controlStr_REGION_T_16_ap_int_ap_int_ap_int_stream_data_7_q0;
    end else begin
        grp_fu_216_p0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage7_11001) & (1'b1 == ap_CS_fsm_pp0_stage7)) | ((1'b0 == ap_block_pp0_stage6_11001) & (1'b1 == ap_CS_fsm_pp0_stage6)) | ((1'b0 == ap_block_pp0_stage5_11001) & (1'b1 == ap_CS_fsm_pp0_stage5)) | ((1'b0 == ap_block_pp0_stage4_11001) & (1'b1 == ap_CS_fsm_pp0_stage4)) | ((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        grp_fu_222_ce = 1'b1;
    end else begin
        grp_fu_222_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_222_p0 = run_controlStr_REGION_T_16_ap_int_ap_int_ap_int_stream_data_q0;
    end else if (((1'b0 == ap_block_pp0_stage6) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6))) begin
        grp_fu_222_p0 = run_controlStr_REGION_T_16_ap_int_ap_int_ap_int_stream_data_1_q0;
    end else if (((1'b0 == ap_block_pp0_stage4) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        grp_fu_222_p0 = run_controlStr_REGION_T_16_ap_int_ap_int_ap_int_stream_data_2_q0;
    end else if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        grp_fu_222_p0 = run_controlStr_REGION_T_16_ap_int_ap_int_ap_int_stream_data_3_load_reg_782;
    end else if (((1'b0 == ap_block_pp0_stage7) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
        grp_fu_222_p0 = run_controlStr_REGION_T_16_ap_int_ap_int_ap_int_stream_data_4_q0;
    end else if (((1'b0 == ap_block_pp0_stage5) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
        grp_fu_222_p0 = run_controlStr_REGION_T_16_ap_int_ap_int_ap_int_stream_data_5_q0;
    end else if (((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        grp_fu_222_p0 = run_controlStr_REGION_T_16_ap_int_ap_int_ap_int_stream_data_6_q0;
    end else if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_222_p0 = run_controlStr_REGION_T_16_ap_int_ap_int_ap_int_stream_data_7_q0;
    end else begin
        grp_fu_222_p0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage5_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
        run_controlStr_REGION_T_16_ap_int_ap_int_ap_int_stream_data_1_ce0 = 1'b1;
    end else begin
        run_controlStr_REGION_T_16_ap_int_ap_int_ap_int_stream_data_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        run_controlStr_REGION_T_16_ap_int_ap_int_ap_int_stream_data_2_ce0 = 1'b1;
    end else begin
        run_controlStr_REGION_T_16_ap_int_ap_int_ap_int_stream_data_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        run_controlStr_REGION_T_16_ap_int_ap_int_ap_int_stream_data_3_ce0 = 1'b1;
    end else begin
        run_controlStr_REGION_T_16_ap_int_ap_int_ap_int_stream_data_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage6_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6))) begin
        run_controlStr_REGION_T_16_ap_int_ap_int_ap_int_stream_data_4_ce0 = 1'b1;
    end else begin
        run_controlStr_REGION_T_16_ap_int_ap_int_ap_int_stream_data_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage4_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        run_controlStr_REGION_T_16_ap_int_ap_int_ap_int_stream_data_5_ce0 = 1'b1;
    end else begin
        run_controlStr_REGION_T_16_ap_int_ap_int_ap_int_stream_data_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        run_controlStr_REGION_T_16_ap_int_ap_int_ap_int_stream_data_6_ce0 = 1'b1;
    end else begin
        run_controlStr_REGION_T_16_ap_int_ap_int_ap_int_stream_data_6_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        run_controlStr_REGION_T_16_ap_int_ap_int_ap_int_stream_data_7_ce0 = 1'b1;
    end else begin
        run_controlStr_REGION_T_16_ap_int_ap_int_ap_int_stream_data_7_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage7_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
        run_controlStr_REGION_T_16_ap_int_ap_int_ap_int_stream_data_ce0 = 1'b1;
    end else begin
        run_controlStr_REGION_T_16_ap_int_ap_int_ap_int_stream_data_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_done_reg == 1'b0))) begin
        taskId_c_blk_n = taskId_c_full_n;
    end else begin
        taskId_c_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        taskId_c_write = 1'b1;
    end else begin
        taskId_c_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((ap_start == 1'b0) & (ap_idle_pp0_1to3 == 1'b1)) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        ap_ST_fsm_pp0_stage2 : begin
            if ((1'b0 == ap_block_pp0_stage2_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end
        end
        ap_ST_fsm_pp0_stage3 : begin
            if ((1'b0 == ap_block_pp0_stage3_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end
        end
        ap_ST_fsm_pp0_stage4 : begin
            if (((1'b0 == ap_block_pp0_stage4_subdone) & (ap_reset_idle_pp0 == 1'b0))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage5;
            end else if (((1'b0 == ap_block_pp0_stage4_subdone) & (ap_reset_idle_pp0 == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage4;
            end
        end
        ap_ST_fsm_pp0_stage5 : begin
            if ((1'b0 == ap_block_pp0_stage5_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage5;
            end
        end
        ap_ST_fsm_pp0_stage6 : begin
            if ((1'b0 == ap_block_pp0_stage6_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage6;
            end
        end
        ap_ST_fsm_pp0_stage7 : begin
            if ((1'b0 == ap_block_pp0_stage7_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage7;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign and_ln85_1_fu_352_p2 = (or_ln85_6_fu_346_p2 & or_ln85_4_fu_340_p2);

assign and_ln85_2_fu_405_p2 = (or_ln85_8_fu_393_p2 & or_ln85_10_fu_399_p2);

assign and_ln85_3_fu_458_p2 = (or_ln85_14_fu_452_p2 & or_ln85_12_fu_446_p2);

assign and_ln85_4_fu_511_p2 = (or_ln85_17_fu_505_p2 & or_ln85_16_fu_499_p2);

assign and_ln85_5_fu_564_p2 = (or_ln85_19_fu_558_p2 & or_ln85_18_fu_552_p2);

assign and_ln85_6_fu_617_p2 = (or_ln85_21_fu_611_p2 & or_ln85_20_fu_605_p2);

assign and_ln85_7_fu_670_p2 = (or_ln85_23_fu_664_p2 & or_ln85_22_fu_658_p2);

assign and_ln85_fu_299_p2 = (or_ln85_fu_287_p2 & or_ln85_2_fu_293_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_pp0_stage2 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_pp0_stage3 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_pp0_stage4 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_pp0_stage5 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_pp0_stage6 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_pp0_stage7 = ap_CS_fsm[32'd7];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_00001 = ((ap_enable_reg_pp0_iter0 == 1'b1) & ((taskId_c_full_n == 1'b0) | (ap_done_reg == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_01001 = ((ap_enable_reg_pp0_iter0 == 1'b1) & ((taskId_c_full_n == 1'b0) | (ap_done_reg == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_enable_reg_pp0_iter0 == 1'b1) & ((taskId_c_full_n == 1'b0) | (ap_done_reg == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001_ignoreCallOp201 = ((ap_enable_reg_pp0_iter0 == 1'b1) & ((taskId_c_full_n == 1'b0) | (ap_done_reg == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_enable_reg_pp0_iter0 == 1'b1) & ((taskId_c_full_n == 1'b0) | (ap_done_reg == 1'b1)));
end

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_00001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_11001_ignoreCallOp202 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_00001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_11001_ignoreCallOp195 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3_00001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3_11001_ignoreCallOp196 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage4 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage4_00001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage4_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage4_11001_ignoreCallOp197 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage4_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage5 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage5_00001 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage5_11001 = (ap_done_reg == 1'b1);
end

always @ (*) begin
    ap_block_pp0_stage5_11001_ignoreCallOp198 = (ap_done_reg == 1'b1);
end

always @ (*) begin
    ap_block_pp0_stage5_subdone = (ap_done_reg == 1'b1);
end

assign ap_block_pp0_stage6 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage6_00001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage6_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage6_11001_ignoreCallOp199 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage6_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage7 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage7_00001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage7_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage7_11001_ignoreCallOp200 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage7_subdone = ~(1'b1 == 1'b1);

assign ap_block_state10_pp0_stage1_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state10_pp0_stage1_iter1_ignore_call0 = ~(1'b1 == 1'b1);

assign ap_block_state11_pp0_stage2_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state11_pp0_stage2_iter1_ignore_call0 = ~(1'b1 == 1'b1);

assign ap_block_state12_pp0_stage3_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state12_pp0_stage3_iter1_ignore_call0 = ~(1'b1 == 1'b1);

assign ap_block_state13_pp0_stage4_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state13_pp0_stage4_iter1_ignore_call0 = ~(1'b1 == 1'b1);

assign ap_block_state14_pp0_stage5_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state14_pp0_stage5_iter1_ignore_call0 = ~(1'b1 == 1'b1);

assign ap_block_state15_pp0_stage6_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state15_pp0_stage6_iter1_ignore_call0 = ~(1'b1 == 1'b1);

assign ap_block_state16_pp0_stage7_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state16_pp0_stage7_iter1_ignore_call0 = ~(1'b1 == 1'b1);

assign ap_block_state17_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state17_pp0_stage0_iter2_ignore_call0 = ~(1'b1 == 1'b1);

assign ap_block_state18_pp0_stage1_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state18_pp0_stage1_iter2_ignore_call0 = ~(1'b1 == 1'b1);

assign ap_block_state19_pp0_stage2_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state19_pp0_stage2_iter2_ignore_call0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = ((taskId_c_full_n == 1'b0) | (ap_done_reg == 1'b1));
end

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0_ignore_call0 = ((taskId_c_full_n == 1'b0) | (ap_done_reg == 1'b1));
end

assign ap_block_state20_pp0_stage3_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state20_pp0_stage3_iter2_ignore_call0 = ~(1'b1 == 1'b1);

assign ap_block_state21_pp0_stage4_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state21_pp0_stage4_iter2_ignore_call0 = ~(1'b1 == 1'b1);

assign ap_block_state22_pp0_stage5_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state22_pp0_stage5_iter2_ignore_call0 = ~(1'b1 == 1'b1);

assign ap_block_state23_pp0_stage6_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state23_pp0_stage6_iter2_ignore_call0 = ~(1'b1 == 1'b1);

assign ap_block_state24_pp0_stage7_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state24_pp0_stage7_iter2_ignore_call0 = ~(1'b1 == 1'b1);

assign ap_block_state25_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state25_pp0_stage0_iter3_ignore_call0 = ~(1'b1 == 1'b1);

assign ap_block_state26_pp0_stage1_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state26_pp0_stage1_iter3_ignore_call0 = ~(1'b1 == 1'b1);

assign ap_block_state27_pp0_stage2_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state27_pp0_stage2_iter3_ignore_call0 = ~(1'b1 == 1'b1);

assign ap_block_state28_pp0_stage3_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state28_pp0_stage3_iter3_ignore_call0 = ~(1'b1 == 1'b1);

assign ap_block_state29_pp0_stage4_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state29_pp0_stage4_iter3_ignore_call0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage1_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage1_iter0_ignore_call0 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage2_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage2_iter0_ignore_call0 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage3_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage3_iter0_ignore_call0 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage4_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage4_iter0_ignore_call0 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage5_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage5_iter0_ignore_call0 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage6_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage6_iter0_ignore_call0 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage7_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage7_iter0_ignore_call0 = ~(1'b1 == 1'b1);

assign ap_block_state9_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state9_pp0_stage0_iter1_ignore_call0 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_phi_reg_pp0_iter0_error_write_assign_reg_187 = 'bx;

always @ (*) begin
    ap_predicate_op107_fcmp_state8 = ((or_ln85_5_reg_765 == 1'd0) & (or_ln85_3_reg_752 == 1'd0) & (or_ln85_1_reg_739 == 1'd0));
end

always @ (*) begin
    ap_predicate_op108_fcmp_state8 = ((or_ln85_5_reg_765 == 1'd0) & (or_ln85_3_reg_752 == 1'd0) & (or_ln85_1_reg_739 == 1'd0));
end

always @ (*) begin
    ap_predicate_op109_fcmp_state8 = ((or_ln85_5_reg_765 == 1'd0) & (or_ln85_3_reg_752 == 1'd0) & (or_ln85_1_reg_739 == 1'd0));
end

always @ (*) begin
    ap_predicate_op125_fcmp_state11 = ((or_ln85_7_reg_778 == 1'd0) & (or_ln85_5_reg_765 == 1'd0) & (or_ln85_3_reg_752 == 1'd0) & (or_ln85_1_reg_739 == 1'd0));
end

always @ (*) begin
    ap_predicate_op126_fcmp_state11 = ((or_ln85_7_reg_778 == 1'd0) & (or_ln85_5_reg_765 == 1'd0) & (or_ln85_3_reg_752 == 1'd0) & (or_ln85_1_reg_739 == 1'd0));
end

always @ (*) begin
    ap_predicate_op127_fcmp_state11 = ((or_ln85_7_reg_778 == 1'd0) & (or_ln85_5_reg_765 == 1'd0) & (or_ln85_3_reg_752 == 1'd0) & (or_ln85_1_reg_739 == 1'd0));
end

always @ (*) begin
    ap_predicate_op143_fcmp_state13 = ((or_ln85_9_reg_791 == 1'd0) & (or_ln85_7_reg_778 == 1'd0) & (or_ln85_5_reg_765 == 1'd0) & (or_ln85_3_reg_752 == 1'd0) & (or_ln85_1_reg_739_pp0_iter1_reg == 1'd0));
end

always @ (*) begin
    ap_predicate_op144_fcmp_state13 = ((or_ln85_9_reg_791 == 1'd0) & (or_ln85_7_reg_778 == 1'd0) & (or_ln85_5_reg_765 == 1'd0) & (or_ln85_3_reg_752 == 1'd0) & (or_ln85_1_reg_739_pp0_iter1_reg == 1'd0));
end

always @ (*) begin
    ap_predicate_op145_fcmp_state13 = ((or_ln85_9_reg_791 == 1'd0) & (or_ln85_7_reg_778 == 1'd0) & (or_ln85_5_reg_765 == 1'd0) & (or_ln85_3_reg_752 == 1'd0) & (or_ln85_1_reg_739_pp0_iter1_reg == 1'd0));
end

always @ (*) begin
    ap_predicate_op161_fcmp_state15 = ((or_ln85_11_reg_804 == 1'd0) & (or_ln85_9_reg_791 == 1'd0) & (or_ln85_7_reg_778 == 1'd0) & (or_ln85_5_reg_765 == 1'd0) & (or_ln85_3_reg_752_pp0_iter1_reg == 1'd0) & (or_ln85_1_reg_739_pp0_iter1_reg == 1'd0));
end

always @ (*) begin
    ap_predicate_op162_fcmp_state15 = ((or_ln85_11_reg_804 == 1'd0) & (or_ln85_9_reg_791 == 1'd0) & (or_ln85_7_reg_778 == 1'd0) & (or_ln85_5_reg_765 == 1'd0) & (or_ln85_3_reg_752_pp0_iter1_reg == 1'd0) & (or_ln85_1_reg_739_pp0_iter1_reg == 1'd0));
end

always @ (*) begin
    ap_predicate_op163_fcmp_state15 = ((or_ln85_11_reg_804 == 1'd0) & (or_ln85_9_reg_791 == 1'd0) & (or_ln85_7_reg_778 == 1'd0) & (or_ln85_5_reg_765 == 1'd0) & (or_ln85_3_reg_752_pp0_iter1_reg == 1'd0) & (or_ln85_1_reg_739_pp0_iter1_reg == 1'd0));
end

always @ (*) begin
    ap_predicate_op179_fcmp_state17 = ((or_ln85_13_reg_817 == 1'd0) & (or_ln85_11_reg_804 == 1'd0) & (or_ln85_9_reg_791 == 1'd0) & (or_ln85_7_reg_778 == 1'd0) & (or_ln85_5_reg_765_pp0_iter1_reg == 1'd0) & (or_ln85_3_reg_752_pp0_iter1_reg == 1'd0) & (or_ln85_1_reg_739_pp0_iter1_reg == 1'd0));
end

always @ (*) begin
    ap_predicate_op180_fcmp_state17 = ((or_ln85_13_reg_817 == 1'd0) & (or_ln85_11_reg_804 == 1'd0) & (or_ln85_9_reg_791 == 1'd0) & (or_ln85_7_reg_778 == 1'd0) & (or_ln85_5_reg_765_pp0_iter1_reg == 1'd0) & (or_ln85_3_reg_752_pp0_iter1_reg == 1'd0) & (or_ln85_1_reg_739_pp0_iter1_reg == 1'd0));
end

always @ (*) begin
    ap_predicate_op181_fcmp_state17 = ((or_ln85_13_reg_817 == 1'd0) & (or_ln85_11_reg_804 == 1'd0) & (or_ln85_9_reg_791 == 1'd0) & (or_ln85_7_reg_778 == 1'd0) & (or_ln85_5_reg_765_pp0_iter1_reg == 1'd0) & (or_ln85_3_reg_752_pp0_iter1_reg == 1'd0) & (or_ln85_1_reg_739_pp0_iter1_reg == 1'd0));
end

always @ (*) begin
    ap_predicate_op195_call_state19 = ((or_ln85_15_reg_830 == 1'd0) & (or_ln85_13_reg_817 == 1'd0) & (or_ln85_11_reg_804 == 1'd0) & (or_ln85_9_reg_791 == 1'd0) & (or_ln85_7_reg_778_pp0_iter2_reg == 1'd0) & (or_ln85_5_reg_765_pp0_iter1_reg == 1'd0) & (or_ln85_3_reg_752_pp0_iter1_reg == 1'd0) & (or_ln85_1_reg_739_pp0_iter1_reg == 1'd0));
end

always @ (*) begin
    ap_predicate_op195_call_state19_state18 = ((or_ln85_15_fu_676_p2 == 1'd0) & (or_ln85_13_reg_817 == 1'd0) & (or_ln85_11_reg_804 == 1'd0) & (or_ln85_9_reg_791 == 1'd0) & (or_ln85_7_reg_778_pp0_iter2_reg == 1'd0) & (or_ln85_5_reg_765_pp0_iter1_reg == 1'd0) & (or_ln85_3_reg_752_pp0_iter1_reg == 1'd0) & (or_ln85_1_reg_739_pp0_iter1_reg == 1'd0));
end

always @ (*) begin
    ap_predicate_op89_fcmp_state6 = ((or_ln85_3_reg_752 == 1'd0) & (or_ln85_1_reg_739 == 1'd0));
end

always @ (*) begin
    ap_predicate_op90_fcmp_state6 = ((or_ln85_3_reg_752 == 1'd0) & (or_ln85_1_reg_739 == 1'd0));
end

always @ (*) begin
    ap_predicate_op91_fcmp_state6 = ((or_ln85_3_reg_752 == 1'd0) & (or_ln85_1_reg_739 == 1'd0));
end

assign bitcast_ln85_1_fu_311_p1 = run_controlStr_REGION_T_16_ap_int_ap_int_ap_int_stream_data_6_load_reg_743;

assign bitcast_ln85_2_fu_364_p1 = run_controlStr_REGION_T_16_ap_int_ap_int_ap_int_stream_data_5_load_reg_756;

assign bitcast_ln85_3_fu_417_p1 = run_controlStr_REGION_T_16_ap_int_ap_int_ap_int_stream_data_4_load_reg_769;

assign bitcast_ln85_4_fu_470_p1 = run_controlStr_REGION_T_16_ap_int_ap_int_ap_int_stream_data_3_load_reg_782;

assign bitcast_ln85_5_fu_523_p1 = run_controlStr_REGION_T_16_ap_int_ap_int_ap_int_stream_data_2_load_reg_795;

assign bitcast_ln85_6_fu_576_p1 = run_controlStr_REGION_T_16_ap_int_ap_int_ap_int_stream_data_1_load_reg_808;

assign bitcast_ln85_7_fu_629_p1 = run_controlStr_REGION_T_16_ap_int_ap_int_ap_int_stream_data_load_reg_821;

assign bitcast_ln85_fu_258_p1 = run_controlStr_REGION_T_16_ap_int_ap_int_ap_int_stream_data_7_load_reg_730;

assign grp_find_region_fu_198_ap_start = grp_find_region_fu_198_ap_start_reg;

assign icmp_ln85_10_fu_540_p2 = ((tmp_15_fu_526_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln85_11_fu_546_p2 = ((trunc_ln85_5_fu_536_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln85_12_fu_593_p2 = ((tmp_18_fu_579_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln85_13_fu_599_p2 = ((trunc_ln85_6_fu_589_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln85_14_fu_646_p2 = ((tmp_21_fu_632_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln85_15_fu_652_p2 = ((trunc_ln85_7_fu_642_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln85_1_fu_281_p2 = ((trunc_ln85_fu_271_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln85_2_fu_328_p2 = ((tmp_5_fu_314_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln85_3_fu_334_p2 = ((trunc_ln85_1_fu_324_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln85_4_fu_381_p2 = ((tmp_9_fu_367_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln85_5_fu_387_p2 = ((trunc_ln85_2_fu_377_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln85_6_fu_434_p2 = ((tmp_7_fu_420_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln85_7_fu_440_p2 = ((trunc_ln85_3_fu_430_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln85_8_fu_487_p2 = ((tmp_12_fu_473_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln85_9_fu_493_p2 = ((trunc_ln85_4_fu_483_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln85_fu_275_p2 = ((tmp_1_fu_261_p4 != 8'd255) ? 1'b1 : 1'b0);

assign or_ln85_10_fu_399_p2 = (grp_fu_222_p2 | grp_fu_216_p2);

assign or_ln85_11_fu_570_p2 = (grp_fu_210_p2 | and_ln85_5_fu_564_p2);

assign or_ln85_12_fu_446_p2 = (icmp_ln85_7_fu_440_p2 | icmp_ln85_6_fu_434_p2);

assign or_ln85_13_fu_623_p2 = (grp_fu_210_p2 | and_ln85_6_fu_617_p2);

assign or_ln85_14_fu_452_p2 = (grp_fu_222_p2 | grp_fu_216_p2);

assign or_ln85_15_fu_676_p2 = (grp_fu_210_p2 | and_ln85_7_fu_670_p2);

assign or_ln85_16_fu_499_p2 = (icmp_ln85_9_fu_493_p2 | icmp_ln85_8_fu_487_p2);

assign or_ln85_17_fu_505_p2 = (grp_fu_222_p2 | grp_fu_216_p2);

assign or_ln85_18_fu_552_p2 = (icmp_ln85_11_fu_546_p2 | icmp_ln85_10_fu_540_p2);

assign or_ln85_19_fu_558_p2 = (grp_fu_222_p2 | grp_fu_216_p2);

assign or_ln85_1_fu_305_p2 = (grp_fu_210_p2 | and_ln85_fu_299_p2);

assign or_ln85_20_fu_605_p2 = (icmp_ln85_13_fu_599_p2 | icmp_ln85_12_fu_593_p2);

assign or_ln85_21_fu_611_p2 = (grp_fu_222_p2 | grp_fu_216_p2);

assign or_ln85_22_fu_658_p2 = (icmp_ln85_15_fu_652_p2 | icmp_ln85_14_fu_646_p2);

assign or_ln85_23_fu_664_p2 = (grp_fu_222_p2 | grp_fu_216_p2);

assign or_ln85_2_fu_293_p2 = (grp_fu_222_p2 | grp_fu_216_p2);

assign or_ln85_3_fu_358_p2 = (grp_fu_210_p2 | and_ln85_1_fu_352_p2);

assign or_ln85_4_fu_340_p2 = (icmp_ln85_3_fu_334_p2 | icmp_ln85_2_fu_328_p2);

assign or_ln85_5_fu_411_p2 = (grp_fu_210_p2 | and_ln85_2_fu_405_p2);

assign or_ln85_6_fu_346_p2 = (grp_fu_222_p2 | grp_fu_216_p2);

assign or_ln85_7_fu_464_p2 = (grp_fu_210_p2 | and_ln85_3_fu_458_p2);

assign or_ln85_8_fu_393_p2 = (icmp_ln85_5_fu_387_p2 | icmp_ln85_4_fu_381_p2);

assign or_ln85_9_fu_517_p2 = (grp_fu_210_p2 | and_ln85_4_fu_511_p2);

assign or_ln85_fu_287_p2 = (icmp_ln85_fu_275_p2 | icmp_ln85_1_fu_281_p2);

assign run_controlStr_REGION_T_16_ap_int_ap_int_ap_int_stream_data_1_address0 = run_controlStr_REGION_T_16_ap_int_ap_int_ap_int_stream_data_1_addr_reg_695_pp0_iter1_reg;

assign run_controlStr_REGION_T_16_ap_int_ap_int_ap_int_stream_data_2_address0 = run_controlStr_REGION_T_16_ap_int_ap_int_ap_int_stream_data_2_addr_reg_700_pp0_iter1_reg;

assign run_controlStr_REGION_T_16_ap_int_ap_int_ap_int_stream_data_3_address0 = run_controlStr_REGION_T_16_ap_int_ap_int_ap_int_stream_data_3_addr_reg_705;

assign run_controlStr_REGION_T_16_ap_int_ap_int_ap_int_stream_data_4_address0 = run_controlStr_REGION_T_16_ap_int_ap_int_ap_int_stream_data_4_addr_reg_710;

assign run_controlStr_REGION_T_16_ap_int_ap_int_ap_int_stream_data_5_address0 = run_controlStr_REGION_T_16_ap_int_ap_int_ap_int_stream_data_5_addr_reg_715;

assign run_controlStr_REGION_T_16_ap_int_ap_int_ap_int_stream_data_6_address0 = run_controlStr_REGION_T_16_ap_int_ap_int_ap_int_stream_data_6_addr_reg_720;

assign run_controlStr_REGION_T_16_ap_int_ap_int_ap_int_stream_data_7_address0 = zext_ln80_fu_246_p1;

assign run_controlStr_REGION_T_16_ap_int_ap_int_ap_int_stream_data_address0 = run_controlStr_REGION_T_16_ap_int_ap_int_ap_int_stream_data_addr_reg_690_pp0_iter1_reg;

assign taskId_c_din = p_read1;

assign tmp_12_fu_473_p4 = {{bitcast_ln85_4_fu_470_p1[30:23]}};

assign tmp_15_fu_526_p4 = {{bitcast_ln85_5_fu_523_p1[30:23]}};

assign tmp_18_fu_579_p4 = {{bitcast_ln85_6_fu_576_p1[30:23]}};

assign tmp_1_fu_261_p4 = {{bitcast_ln85_fu_258_p1[30:23]}};

assign tmp_21_fu_632_p4 = {{bitcast_ln85_7_fu_629_p1[30:23]}};

assign tmp_5_fu_314_p4 = {{bitcast_ln85_1_fu_311_p1[30:23]}};

assign tmp_7_fu_420_p4 = {{bitcast_ln85_3_fu_417_p1[30:23]}};

assign tmp_9_fu_367_p4 = {{bitcast_ln85_2_fu_364_p1[30:23]}};

assign trunc_ln85_1_fu_324_p1 = bitcast_ln85_1_fu_311_p1[22:0];

assign trunc_ln85_2_fu_377_p1 = bitcast_ln85_2_fu_364_p1[22:0];

assign trunc_ln85_3_fu_430_p1 = bitcast_ln85_3_fu_417_p1[22:0];

assign trunc_ln85_4_fu_483_p1 = bitcast_ln85_4_fu_470_p1[22:0];

assign trunc_ln85_5_fu_536_p1 = bitcast_ln85_5_fu_523_p1[22:0];

assign trunc_ln85_6_fu_589_p1 = bitcast_ln85_6_fu_576_p1[22:0];

assign trunc_ln85_7_fu_642_p1 = bitcast_ln85_7_fu_629_p1[22:0];

assign trunc_ln85_fu_271_p1 = bitcast_ln85_fu_258_p1[22:0];

assign zext_ln80_fu_246_p1 = p_read1;

endmodule //run_run_test
